repos:
  - repo: local
    hooks:

      - id: flake8
        name: flake8
        entry: flake8 src/
        files: \.py$
        language: python
        additional_dependencies: [ flake8-docstrings ]


      - id: black
        name: black
        entry: black src
        files: \.py$
        language: python

      - id: mypy
        name: mypy
        entry: mypy
        args: [ --explicit-package-bases,  --ignore-missing-imports, --follow-imports=skip, --strict-optional ]
        language: python
        types: [ python ]
        require_serial: true


      - id: isort
        name: isort
        entry: isort
        args: [ "--profile", "black", "--filter-files" ]
        language: system
        types: [ python ]
